# Generated by Django 2.1.5 on 2019-01-04 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('race', models.CharField(max_length=15)),
                ('orientation', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=10)),
                ('transplant', models.BooleanField(null=True)),
                ('location_city', models.CharField(max_length=20)),
                ('location_state', models.CharField(max_length=20)),
            ],
        ),
    ]
