# Generated by Django 2.1.5 on 2019-01-05 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190105_0001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='size',
            new_name='org_size',
        ),
    ]
