# Generated by Django 2.1.5 on 2019-01-06 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190105_2046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adie',
            options={'ordering': ['race'], 'verbose_name': 'adie', 'verbose_name_plural': 'adies'},
        ),
    ]
