# Generated by Django 2.1.5 on 2019-01-06 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190106_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adie',
            name='gender',
            field=models.CharField(choices=[('female', 'female'), ('non-binary', 'non-binary'), ('trans', 'transgender'), ('two-spirited', 'two-spirited'), ('male', 'male')], max_length=20),
        ),
        migrations.AlterField(
            model_name='adie',
            name='race',
            field=models.CharField(choices=[('Black', 'African American'), ('Latinx', 'Hispanic'), ('Latinx', 'Latino'), ('White', 'European American'), ('White', 'Caucasian'), ('Asian', 'Asian American'), ('Indigenous', 'Native'), ('Indigenous', 'Native American'), ('Indigenous', 'Alaska Native'), ('Pacific Islander', 'Native Hawaiian')], max_length=20),
        ),
        migrations.AlterField(
            model_name='adie',
            name='transplant',
            field=models.BooleanField(default=False),
        ),
    ]
