# Generated by Django 2.1.5 on 2019-01-06 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190106_0637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='adies',
        ),
    ]
